AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infrastructure pour une SPA hébergé sur un bucket S3 et derriere un CloudFront pour optimisée pour les coûts'

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resources names
    Type: String
    Default: prod

  BucketName:
    Type: String
    Description: Nom du bucket S3 pour héberger la spa
    Default: mon-super-bucket

  CloudFrontPriceClass:
    Type: String
    Description: Classe de prix CloudFront (détermine la couverture géographique)
    Default: PriceClass_100
    AllowedValues:
      - PriceClass_100
      - PriceClass_200
      - PriceClass_All

  EnableLogging:
    Type: String
    Description: Activer la journalisation CloudFront (génère des coûts supplémentaires)
    Default: "false"
    AllowedValues:
      - "true"
      - "false"

  FinalEndpoint:
    Description: Final application domain name. Will also be passed to lambdas for platform endpoint
    Type: String
    Default: "mon-super-nom-de-domaine"

  ApplicationCode:
    Description: An application name that will be prefixed to resources names (only [a-z-])
    Type: String
    Default: myapplication
    AllowedPattern: ^[a-z-]+$
    MinLength: 4
    MaxLength: 16

  SSLCertificateArn:
    Description: Arn for SSL Certificate generated by CertificateManager
    Type: String
    Default: "arn:aws:acm:us-east-1:ACCOUNT_ID:certificate/CERTIFICATE_ID"

  App:
    Type: String
    Description: Nom de l'application pour le tagging
    Default: blog-204nocontent

  Env:
    Type: String
    Description: Environnement pour le tagging (dev, staging, prod)
    Default: prod

Conditions:
  EnableLoggingCondition: !Equals [!Ref EnableLogging, "true"]
Resources:
  #############################################
  #### CLOUDFRONT
  #############################################

  # Distribution CloudFront
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      Tags:
        - Key: App
          Value: !Ref App
        - Key: Env
          Value: !Ref Env
      DistributionConfig:
        Comment: !Join [ '-', [ !Ref EnvironmentName, !Ref ApplicationCode, 'distribution' ] ]
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        PriceClass: !Ref CloudFrontPriceClass
        Origins:
          - DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ""  # Vide pour utiliser OAC
            OriginAccessControlId: !Ref OriginAccessControl
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 86400    # 1 jour
          MinTTL: 0
          MaxTTL: 31536000    # 1 an
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        Aliases:
          - !Ref FinalEndpoint
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        # Optimisation des coûts: Désactiver la journalisation par défaut
        Logging: !If
          - EnableLoggingCondition
          - Bucket: !GetAtt WebsiteBucket.DomainName
            Prefix: "cf-logs/"
            IncludeCookies: false
          - !Ref AWS::NoValue

  # Origin Access Control pour CloudFront (remplace OAI)
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${EnvironmentName}-${ApplicationCode}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  #############################################
  #### BUCKETS S3
  #############################################
  # Bucket S3 pour héberger le contenu statique
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
            MaxAge: 3000
      # Optimisation des coûts: Ajout d'une politique de cycle de vie pour supprimer les anciennes versions
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 1
          - Id: AbortIncompleteMultipartUpload
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
      Tags:
        - Key: App
          Value: !Ref App
        - Key: Env
          Value: !Ref Env

  # Politique du bucket S3
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Sub "${WebsiteBucket.Arn}/*"
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

Outputs:
  WebsiteBucketName:
    Description: Nom du bucket S3
    Value: !Ref WebsiteBucket

  CloudFrontDistributionId:
    Description: ID de la distribution CloudFront
    Value: !Ref CloudFrontDistribution

  CloudFrontDomainName:
    Description: Nom de domaine CloudFront
    Value: !GetAtt CloudFrontDistribution.DomainName

  CloudFrontURL:
    Description: URL du site via CloudFront
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"

  CustomDomainURL:
    Description: URL du site avec domaine personnalisé
    Value: !Sub "https://${FinalEndpoint}"

  EstimatedMonthlyCost:
    Description: Estimation des coûts mensuels (approximatif)
    Value: "S3 (premiers 50 To/mois): $0.023/Go + CloudFront (PriceClass_100): $0.085/Go"